name: Metrics
on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alltilla
          template: classic
          base: ""
          config_display: large
          config_octicon: yes
          config_timezone: Europe/Budapest
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_types: commit
